print('Hello')
print('Hello')
print('Testirovanie')
print('Stroka 4')

print('Добавить строку 9')
print('Добавить строку 10')
print('Добавить строку 11')
print('Добавить строку 12')
print('Добавить строку 13')
print('Добавить строку 14')
print('Добавить строку 15')
print('Добавить строку 16')
print('Добавить строку 17')
print('Добавить строку 18')
print('Добавить строку 19')
